### ISSUE TITLE
node module export

### ISSUE THREAD

**Issue by ftann** [TomWHall/p2Pixi#2]
the built node module seems to miss an export like:

``` javascript
exports = module.exports = P2Pixi;
```

after importing the module in node with:

``` javascript
var P2Pixi = require('p2Pixi');
```

P2Pixi is undefined.

as a quick workaround i wrapped an iffe around the whole p2Pixi.js source and added the exports at the end.

**Comment by TomWHall** [comment]
Hi, sorry for the delay. I recently converted the classes to CommonJS modules and I'm using Browserify to bundle them. index.js is:

var P2Pixi = module.exports = {
  Game: require('./Game'),
  GameObject: require('./GameObject'),
  PixiAdapter: require('./PixiAdapter')
};

However, within p2Pixi I'm using the global window p2 and PIXI objects, I'm not importing the npm dependencies. I wanted to structure my own code with modules but I didn't want p2 and PIXI being pulled into one giant browser bundle. In any case, when trying to run this within Node, PIXI requires certain things to be polyfilled (such as document). Despite using NPM for my tooling I never really saw this as actually being run within Node. Are you still using it this way?
